version: "3"
services:
  mongodb:
    image: mongo:4.2
    hostname: mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"

  lotterysevice:
    build: ./lottery-service/
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - redis

  web:
    build: ./web/
    ports:
      - "8080:80"

  simpleanimation:
    build: ./simple-animation/
    ports:
      - "8082:80"
